height = 9
spacing = 13

def characters(c):
    config = {
        ":" : [
                '         ',
                '         ',
                '   XXX   ',
                '   XXX   ',
                '         ',
                '   XXX   ',
                '   XXX   ',
                '         ',
                '         ',
        ],
        '0' : [
            'XXXXXXXXX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
        ],
        '1' : [
            '    XX   ',
            '    XX   ',
            '    XX   ',
            '    XX   ',
            '    XX   ',
            '    XX   ',
            '    XX   ',
            '    XX   ',
            '    XX   ',
        ],
        '2': [
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            'XXXXXXXXX',
            'XX       ',
            'XX       ',
            'XX       ',
            'XXXXXXXXX',
        ],
        '3': [
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            'XXXXXXXXX',
        ],
        '4': [
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
        ],
        '5': [
            'XXXXXXXXX',
            'XX       ',
            'XX       ',
            'XX       ',
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            'XXXXXXXXX',
        ],
        '6': [
            'XXXXXXXXX',
            'XX       ',
            'XX       ',
            'XX       ',
            'XXXXXXXXX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
        ],
        '7': [
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
        ],
        '8': [
            'XXXXXXXXX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
        ],
        '9': [
            'XXXXXXXXX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
        ],
    }   

    return config[c]
