def numbers(character):
    config = [
        [
            'XXXXXXXXX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
        ],
        [
            '   XXX   ',
            '   XXX   ',
            '   XXX   ',
            '   XXX   ',
            '   XXX   ',
            '   XXX   ',
            '   XXX   ',
            '   XXX   ',
            '   XXX   ',
        ],
        [
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            'XXXXXXXXX',
            'XX       ',
            'XX       ',
            'XX       ',
            'XXXXXXXXX',
        ],
        [
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            'XXXXXXXXX',
        ],
        [
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
        ],
        [
            'XXXXXXXXX',
            'XX       ',
            'XX       ',
            'XX       ',
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            'XXXXXXXXX',
        ],
        [
            'XXXXXXXXX',
            'XX       ',
            'XX       ',
            'XX       ',
            'XXXXXXXXX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
        ],
        [
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
        ],
        [
            'XXXXXXXXX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
        ],
        [
            'XXXXXXXXX',
            'XX     XX',
            'XX     XX',
            'XX     XX',
            'XXXXXXXXX',
            '       XX',
            '       XX',
            '       XX',
            '       XX',
        ],
    ]   
    return config[int(character)]
